# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageLazyLoading' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'XMLParsing', :git => 'https://github.com/ShawnMoore/XMLParsing.git'

  # Pods for ImageLazyLoading

  target 'ImageLazyLoadingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
